spring.application.name=club

spring.datasource.url=jdbc:mysql://103.24.218.66:3306/siulightdatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&connectTimeout=5000&socketTimeout=10000
spring.datasource.username=wmycg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=9Yc3OvT9ujju

mybatis-plus.configuration.map-underscore-to-camel-case=true
